theme: jekyll-theme-slate
logo: /assets/logo.png
title: " "
description: >
  <center><nobr><a style="color:white" target="_blank" href="mailto:joshua@mervine.net">email</a> |
    <a style="color:white" target="_blank" href="https://github.com/jmervine/">github</a> |
    <a style="color:white" target="_blank" href="https://linkedin.com/in/mervinej">linkedin</a></nobr></center>

show_downloads: false
github:
  is_project_page: false
