theme: jekyll-theme-slate
title: >
  <center><img src="http://www.gravatar.com/avatar/ed808193b8c2c8516715816f90a005b2.jpg?s=75" style="padding:5px 15px 15px; float:left"></center>
description: >
  <center><nobr><a style="color:white" target="_blank" href="mailto:joshua@mervine.net">email</a> ::
    <a style="color:white" target="_blank" href="https://github.com/jmervine/">github</a> ::
    <a style="color:white" target="_blank" href="https://linkedin.com/in/jmervine">linkedin</a></nobr></center>

show_downloads: false
github:
  is_project_page: false
